version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
  system_packages: true

python:
  - |
    import os
    
    # 创建 docs 目录（如果不存在）
    os.makedirs('docs', exist_ok=True)
    
    # 创建 index.rst 文件
    with open('docs/index.rst', 'w') as f:
        f.write("""
    欢迎来到文档
    ============

    .. include:: ../README.md
        :parser: myst_parser.sphinx_
    """)
    
    # 创建 conf.py 文件
    with open('docs/conf.py', 'w') as f:
        f.write("""
    extensions = ['myst_parser']
    source_suffix = {
        '.rst': 'restructuredtext',
        '.md': 'markdown',
    }
    master_doc = 'index'
    """)
