[tool.poetry]
name = "quantease-binance-history"
version = "0.1.0"
description = "fetch binance data easily"
authors = ["river <nachuan.shi.quant@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.9.5"
click = "^8.1.7"
coverage = "^7.6.0"
httpx = "^0.27.0"
loguru = "^0.7.2"
pandas = "1.5.2"

[tool.poetry.group.dev.dependencies]
pendulum = "3.0.0"
tqdm = "^4.66.4"
uvloop = "^0.19.0"
pytest = "^8.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
